### PR TITLE
ENG-431 plural deploy resiliency

### PR DESCRIPTION
**Pull request by zreigz**
## Summary
Add additional retries to TF and helm (1 more retry + a sleep)
Change message at the end of 'plural deploy'

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

### CODE REVIEW

**Comment by DavidSpek** [comment]
@zreigz We actually already have a place where retries are being set for Terraform and Helm. It's in the `deploy.hcl` files. See [here](https://github.com/pluralsh/plural-cli/blob/master/pkg/executor/default.go#L9)

**Comment by zreigz** [comment]
@DavidSpek I've added this retry according to the issue description.  Should I remove this and only change the info message?

**Comment by DavidSpek** [comment]
Yeah I think remove that retry, but leave change to the info message. Then you can change https://github.com/pluralsh/plural-cli/blob/master/pkg/executor/default.go#L29 and https://github.com/pluralsh/plural-cli/blob/master/pkg/executor/default.go#L62 to `2`.

**Comment by zreigz** [comment]
@DavidSpek PTAL

**Review by DavidSpek — APPROVED** [review]
Looks good, thanks for the changes!

**Pull request merged**
