### PR TITLE
feat: sign goreleaser release using cosign custom key-pair

### PR DESCRIPTION
**Pull request by floreks**
## Summary

Tested via test repo: https://github.com/floreks/goreleaser-cosign-test

### UPDATE
Using custom key pair for signing and verification.

I have used a makefile target that can verify the file signature.
```bash
$ make verify
Enter version to verify: 1.1.0
Downloading checksums.txt for tag v1.1.0...
Verifying signature...
Verified OK
Verifying archives...
goreleaser-cosign-test_1.1.0_Darwin_amd64.tar.gz: OK
goreleaser-cosign-test_1.1.0_Darwin_arm64.tar.gz: OK
goreleaser-cosign-test_1.1.0_Linux_amd64.tar.gz: OK
goreleaser-cosign-test_1.1.0_Linux_arm64.tar.gz: OK
goreleaser-cosign-test_1.1.0_Windows_amd64.tar.gz: OK
```

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

### CODE REVIEW

**Review by michaeljguarino — COMMENTED** [review]
I'll ask around, but i have a feeling a lot of IT departments don't have support for oidc issuer based signatures and will require a fixed public key to verify against

**Comment by michaeljguarino** [comment]
@floreks can we just create our own keypair and sign w/ those?  I feel like that's the only way to be safe that it can be used by enterprises that need cosign validation given limitations in their ecosystem

**Comment by floreks** [comment]
Sure, you'd need to add a key secret to the repo secrets for GH action to use it since I don't have permissions to add secrets. You should be able to generate it with cosign.

**Comment by floreks** [comment]
@michaeljguarino I can access the settings view now but it's almost empty. Only `Pages` and `Moderation Options` are available.

**Comment by michaeljguarino** [comment]
Ok I don't see any way for us to give you those perms w/ less than admin, so just generated the keypair for you, they're in COSIGN_PRIVATE_KEY and COSIGN_PASSWORD secrets.  Also the cosign.pub file at the root of the repo will be the public key.

**Review by michaeljguarino — APPROVED** [review]

**Pull request merged**
