### PR TITLE
Use generics to simplify table printing

### PR DESCRIPTION
**Pull request by michaeljguarino**
## Summary
Defines a PrintTable[T] function to eliminate a ton of boilerplate table printing code

## Test Plan
local

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

### CODE REVIEW

**Comment by DavidSpek** [comment]
@michaeljguarino Note that we'll need to make sure the dockerfiles are updated to the latest Go version so that generics are supported when building.

**Comment by zreigz** [comment]
> @zreigz I'm not entirely sure why the unit test is failing here, any idea? It looks like some odd interaction with the git checkout code

I will check this

**Comment by zreigz** [comment]
@michaeljguarino this error is from the system call. Every call of this command `os.Getwd()` in the failing test causes the error. For now, I skipped the test

**Comment by zreigz** [comment]
@michaeljguarino found the problem, I've pushed the fix

**Review by zreigz — APPROVED** [review]
lgtm

**Pull request merged**
