### PR TITLE
ENG-962 fix nil installation

### PR DESCRIPTION
**Pull request by zreigz**
## Summary
This PR fixes nil pointer exceptions. To reproduce it:
Uninstall one of the applications in the UI
Run 'plural deploy' 

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

### CODE REVIEW

**Comment by DavidSpek** [comment]
@zreigz I think this same thing happens with the destroy command.

**Comment by zreigz** [comment]
> @zreigz I think this same thing happens with the destroy command.

@DavidSpek I will check this

**Comment by zreigz** [comment]
@DavidSpek I was trying to reproduce the issue with the destroy command but everything works for me

**Review by DavidSpek — APPROVED** [review]
looks good to me

**Pull request merged**
