### PR TITLE
chore!: Remove deprecated commands and plrlctl binary

### PR DESCRIPTION
**Pull request by maciaszczykm**
Removed `plural` commands: 
- `ai` (only unregistered as it may be restored in a different version in the future)
- `api` (removed all commands besides `create domain`)
- `bounce`
- `build`
- `bundle`
- `clusters`
- `common` (removed some commands connected to repos)
- `deploy`
- `destroy`
- `info`
- `link`
- `log`
- `ops` and `workspace` (replaced by `mgmt`)
- `output`
- `packages`
- `proxy`
- `push`
- `repos`
- `stacks`
- `upgrade`

`auth` and `vpn` were not removed.

Tested `up`, `cd` and `down` commands:

### CODE REVIEW

**Comment by michaeljguarino** [comment]
Can you show the `plural --help` output here?

**Comment by michaeljguarino** [comment]
I say let's get rid of the test/template commands.  Also, get rid of `wkspace vpn`, `wkspace readme` and `wkspace serve`.

Also minor dx improvement that'd be nice to do, move `deployments stacks ...` to just `stacks ...` and `deployments pr ...` to just `pr ...`.  Ideally I think the subcommands should map to the console's sidebar tabs as much as possible.

**Comment by maciaszczykm** [comment]
@michaeljguarino Okay, that makes sense. I will iterate tomorrow.

**Comment by maciaszczykm** [comment]
Current state:

```
➜ plural
NAME:
   plural - Tooling to manage your installed plural applications

USAGE:
   plural [global options] command [command options] [arguments...]

COMMANDS:
   auth             handles authentication to the plural api
   clone            clones and decrypts a plural repo
   down             destroys your management cluster and any apps installed on it
   init             initializes plural within a git repo
   up               sets up your repository and an initial management cluster
   version, v, vsn  gets plural cli version info
   help, h          Shows a list of commands or help for one command

   API:
     api  inspect the plural api

   CD:
     deployments, cd    view and manage plural deployments
     stacks, s          manage infrastructure stacks
     pull-requests, pr  generates and manages pull requests

   User Profile:
     config, conf  reads/modifies cli configuration
     crypto        plural encryption utilities
     profile       manages config profiles for plural
     login         logs into plural and saves credentials to the current config profile
     import        imports plural config from another file

   Workspace:
     management, mgmt  manages installations in your workspace
     preflights        runs provider preflight checks

GLOBAL OPTIONS:
   --profile-file FILE         configure your config.yml profile FILE [$PLURAL_PROFILE_FILE]
   --encryption-key-file FILE  configure your encryption key FILE [$PLURAL_ENCRYPTION_KEY_FILE]
   --debug                     enable debug mode [$PLURAL_DEBUG_ENABLE]
   --help, -h                  show help
```

**Comment by michaeljguarino** [comment]
Is the `plural wkspace kube-init` command removed?  That is the one useful one I remember.   I think i might have thought `plural wkspace mgmt` was the same.  Could also be that the docstring is just off.

**Comment by maciaszczykm** [comment]
@michaeljguarino `plural mgmt` has `kube-init` inside:

```
➜ plural mgmt
NAME:
   plural management - manages installations in your workspace

USAGE:
   plural management command [command options] [arguments...]

COMMANDS:
   kube-init  generates kubernetes credentials for this subworkspace
   cluster    list the nodes in your cluster

OPTIONS:
   --help, -h  show help
   ```

**Review by michaeljguarino — APPROVED** [review]

**Comment by harleyharl** [comment]
Can anyone please explain why the build command was deleted? And how we can build using the CLI since this was merged?

**Pull request merged**
