### PR TITLE
add validator to update kubeconfig

### PR DESCRIPTION
**Pull request by zreigz**
## Summary
Update kubeconfig before all kube commands, crd and helm install

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

### CODE REVIEW

**Review by michaeljguarino — COMMENTED** [review]
I think you need to cover `plural watch` too

**Review by michaeljguarino — COMMENTED** [review]
I think this would also be needed in the plain `plural bounce` command too

**Comment by zreigz** [comment]
@michaeljguarino PTAL

**Review by michaeljguarino — APPROVED** [review]
We should follow onto this and see if there's a way to not actually run the aws/gcloud/etc command if its been run before, and just do a kubeconfig context switch, but that can be done later

**Pull request merged**
